#!/usr/bin/env python3
"""Regenerates extension/content/paper.css (design tokens + 8-bit border art).

Edit the colours below and run:  python3 tools/gen-paper.py
"""
from pathlib import Path
from urllib.parse import quote

INK = "#2b2419"; PAPER = "#f3ead3"; ACCENT = "#d4a92c"; RED = "#b5442a"
PAPER_2 = "#e9dfc2"; PAPER_3 = "#ddd1ad"; INK_2 = "#6f6350"; INK_3 = "#a89a80"; MOSS = "#5d6f3f"


def svg(w, h, body, vb=None):
    vb = vb or f"0 0 {w // 4} {h // 4}"
    s = f'<svg xmlns="http://www.w3.org/2000/svg" width="{w}" height="{h}" viewBox="{vb}" shape-rendering="crispEdges">{body}</svg>'
    return 'url("data:image/svg+xml,' + quote(s, safe="/:=, ") + '")'


# 12x12 pixel grids, 4 CSS px per pixel -> 48x48 images, border-image slice 16.
def card(fill, border=INK, shadow=INK, thick=False, shadow_on=True):
    if thick:
        sh = f'<rect x="2" y="2" width="10" height="10" fill="{shadow}"/>' if shadow_on else ""
        outline = f'<path d="M1 0H9V1H10V9H9V10H1V9H0V1H1Z" fill="{border}"/>'
        inner = f'<rect x="2" y="2" width="6" height="6" fill="{fill}"/>'
    else:
        sh = f'<rect x="1" y="1" width="11" height="11" fill="{shadow}"/>' if shadow_on else ""
        outline = f'<path d="M1 0H10V1H11V10H10V11H1V10H0V1H1Z" fill="{border}"/>'
        inner = f'<rect x="1" y="1" width="9" height="9" fill="{fill}"/>'
    return svg(48, 48, sh + outline + inner)


tokens = {
    "card": card(PAPER),
    "card-focus": card(PAPER, thick=True),
    "card-ink": card(INK, shadow_on=False),
    "card-accent": card(ACCENT),
    "card-accent-focus": card(ACCENT, thick=True),
    "card-red": card(PAPER, border=RED, shadow=RED),
    "card-flat": card(PAPER, shadow_on=False),
}
dither_light = svg(4, 4, f'<rect width="1" height="1" fill="{INK}" fill-opacity="0.3"/><rect x="1" y="1" width="1" height="1" fill="{INK}" fill-opacity="0.3"/>', vb="0 0 2 2")
dither = svg(4, 4, f'<rect width="1" height="1" fill="{INK}"/><rect x="1" y="1" width="1" height="1" fill="{INK}"/>', vb="0 0 2 2")
grain = svg(24, 24, f'<rect x="1" y="2" width="1" height="1" fill="{INK}" fill-opacity="0.05"/><rect x="4" y="0" width="1" height="1" fill="{INK}" fill-opacity="0.035"/><rect x="3" y="4" width="1" height="1" fill="{INK}" fill-opacity="0.045"/><rect x="0" y="5" width="1" height="1" fill="{INK}" fill-opacity="0.03"/>', vb="0 0 6 6")

CSS = f"""/* Pioneer TV paper design system: tokens and 8-bit primitives shared by the
   launcher, the overlays on other sites and the settings page.
   GENERATED by tools/gen-paper.py; edit the colours there and rerun it. */
:root {{
  --pioneertv-paper: {PAPER};
  --pioneertv-paper-2: {PAPER_2};
  --pioneertv-paper-3: {PAPER_3};
  --pioneertv-ink: {INK};
  --pioneertv-ink-2: {INK_2};
  --pioneertv-ink-3: {INK_3};
  --pioneertv-accent: {ACCENT};
  --pioneertv-red: {RED};
  --pioneertv-moss: {MOSS};
  --pioneertv-serif: "EB Garamond", "Libertinus Serif", Georgia, "Times New Roman", serif;
  --pioneertv-pixel: "Silkscreen", "Press Start 2P", "Courier New", monospace;
  --pioneertv-px: 4px;  /* one 8-bit pixel */
  --pioneertv-card: {tokens['card']};
  --pioneertv-card-focus: {tokens['card-focus']};
  --pioneertv-card-ink: {tokens['card-ink']};
  --pioneertv-card-accent: {tokens['card-accent']};
  --pioneertv-card-accent-focus: {tokens['card-accent-focus']};
  --pioneertv-card-red: {tokens['card-red']};
  --pioneertv-card-flat: {tokens['card-flat']};
  --pioneertv-dither: {dither};
  --pioneertv-dither-light: {dither_light};
  --pioneertv-grain: {grain};
}}

/* A paper card with a 1px ink border, notched corners and a hard shadow.
   The border-image draws everything; keep background transparent. */
.pioneertv-card, .pioneertv-card-focus, .pioneertv-card-ink, .pioneertv-card-accent, .pioneertv-card-red, .pioneertv-card-flat {{
  border: calc(var(--pioneertv-px) * 4) solid transparent;
  border-image-slice: 16 fill;
  border-image-width: calc(var(--pioneertv-px) * 4);
  border-image-repeat: stretch;
  background: transparent;
  image-rendering: pixelated;
  /* the shadow lives inside the border box: pull content off it */
  padding-right: var(--pioneertv-px); padding-bottom: var(--pioneertv-px);
}}
.pioneertv-card {{ border-image-source: var(--pioneertv-card); }}
.pioneertv-card-focus {{ border-image-source: var(--pioneertv-card-focus); }}
.pioneertv-card-ink {{ border-image-source: var(--pioneertv-card-ink); color: var(--pioneertv-paper); }}
.pioneertv-card-accent {{ border-image-source: var(--pioneertv-card-accent); }}
.pioneertv-card-red {{ border-image-source: var(--pioneertv-card-red); }}
.pioneertv-card-flat {{ border-image-source: var(--pioneertv-card-flat); }}

.pioneertv-icon {{ display: inline-block; vertical-align: -0.15em; width: 1em; height: 1em; }}
.pioneertv-dither {{ background-image: var(--pioneertv-dither); background-size: var(--pioneertv-px) var(--pioneertv-px); }}

/* Key cap: A, B, START … */
.pioneertv-kbd {{
  display: inline-block; min-width: 1.5em; padding: 0.15em 0.35em 0.05em; text-align: center;
  font-family: var(--pioneertv-pixel); font-size: 0.8em; line-height: 1;
  color: var(--pioneertv-paper); background: var(--pioneertv-ink);
  box-shadow: var(--pioneertv-px) var(--pioneertv-px) 0 var(--pioneertv-ink-3);
}}
"""
out = Path(__file__).resolve().parent.parent / "extension" / "content" / "paper.css"
out.write_text(CSS)
print(f"wrote {out} ({len(CSS)} bytes)")
